services:
  postgres:
    image: postgres:17-alpine
    container_name: gastromind-db
    environment:
      POSTGRES_DB: gastromind
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: gastromind-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning


volumes:
  postgres_data: