services:
  postgres:
    image: postgres
    container_name: gastromind-db
    environment:
      POSTGRES_DB: gastromind
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"


  redis:
    image: redis
    container_name: gastromind-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  worker:
    build: ./worker
    container_name: gastromind-worker
    environment:
     - DB_HOST=postgres
     - REDIS_HOST=redis
    depends_on:
     - postgres
     - redis
